[package]
name = "b_plus_tree"
version = "0.0.1"
authors = ["yusuke kataoka <yusuke.kataoka09@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"
license-file = "LICENSE"

panic = "abort"

[dev-dependencies] 
rand = "0.7.3"

[lib]
bench = false